services:
  sleeper-api:
    build:
      context: .
      dockerfile: apps/sleeper-api/Dockerfile
      target: development
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/reservation?authSource=admin
    env_file:
      - .env
    networks:
      - microservices-network
    restart: unless-stopped
    depends_on:
      - mongodb

  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
      target: development
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=development
      - PORT=4001
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/reservation?authSource=admin
    env_file:
      - .env
    networks:
      - microservices-network
    restart: unless-stopped
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: reservation
    volumes:
      - mongodb_data:/data/db
    networks:
      - microservices-network
    restart: unless-stopped

networks:
  microservices-network:
    driver: bridge

volumes:
  mongodb_data:
